# Generated by Django 3.1.2 on 2020-11-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20201125_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='post_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
