# Generated by Django 3.1.2 on 2020-11-26 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_subject_post_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['-post_time']},
        ),
    ]
