# Generated by Django 3.1.2 on 2020-11-26 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20201126_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='text',
        ),
    ]
